# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Release Details
cf_project=313402
release_type=release

# Env Details
mc_version=1.21.1
mc_version_range=[1.21.1,1.22)
neo_version=21.1.164
neo_version_range=[21.1.164,)
loader_version_range=[1,)
mapping_channel=parchment
parchment_mc_version=1.21.1
parchment_map_version=2024.11.17

# Mod Details
mod_id=projecteintegration
mod_name=ProjectE-Integration
mod_version=8.2.0
mod_license=MIT
mod_group_id=com.tagnumelite.projecteintegration
mod_authors=TagnumElite
mod_description=ProjectE Integration is a mod for adding support for mapping recipes from other mods to something that ProjectE understands and is able to convert to emc with.

# ==== [ Project Dependencies ] ====
projecte_version=PE1.0.0B
version_projecte=6301953

# - Runtime

version_alchemylib=1.20.1-1.0.29
# All The Ores: 3.1.6
version_alltheores=6118610
# AE JEI: 1.2.0
version_ae_jei=5748513
version_architectury=13.0.8
# Athena: 4.0.1
version_athena=5629395
# Balm: 21.0.33
version_balm=6319698
version_brandonscore=3.2.1.+
version_chemlib=1.20.1-2.0.18
# Citadel: 2.5.3
version_citadel=5075402
version_codechickenlib=4.6.0.+
#version_ctm=1.19.2-1.1.6+8
version_cucumber=8.0.10
version_curios=9.4.2+1.21.1
# Cyclops Core: 1.25.7
version_cyclopscore=6230091
version_datapackanvil=1.20.1-5.0.1
# FTB Library: 1902.3.9-build.144
#version_ftb_library=3963543
version_geckolib=1.21.1:4.7.5.1
version_jei=19.21.0.247
#version_mantle=1.18.2-1.9.9
version_modonomicon=1.114.0
# Mytrees: 1.2.0-31
#version_myrtrees=3824947
version_novacore=1.21.0-3.0.0-build.2
#version_obfuscate=3336021
#version_observerlib=3333962
version_patchouli=1.21-88-NEOFORGE
# Resourceful Lib: NeoForge-3.0.12
version_resourceful_lib=5973188
version_titanium=1.21-4.0.28
version_smartbrainlib=1.16.7
# Structure Gel API: 2.15.0
version_structuregelapi=4804139

# - Optional

# Alex's Caves: 1.1.1
version_alexcaves=5128730
version_alchemistry=1.20.1-2.3.4
# Allthemodium: 2.8.10
version_allthemodium=6135138
version_appliedenergistics=19.2.4
# Ars Nouveau: 5.7.1
version_arsnouveau=6316304
#version_astralsorcery=3333980
# Blood Magic: 3.3.2-44
version_bloodmagic=4779711
# Blue Skies: 1.3.29
version_blueskies=4765673
version_botania=1.20.1-443-FORGE
# Chipped: 4.0.2
version_chipped=5813117
#version_cofhcore=10.2.1.+
# CompactCrafting: 3.1.0
#version_compactcrafting=4145295
# Corail Woodcutter: 3.4.2
version_corail_woodcutter=5749639
version_create=6.0.4
version_draconicevolution=3.1.2.588
# Elemental Craft: 6.0.1
version_elementalcraft=4800163
# EvilCraft: 1.2.68
version_evilcraft=6296089
version_exnihilo_sequentia=1.21-7.0.0-build.1-beta
version_extendedcrafting=7.0.3
# Farmer's Delight: 1.2.7
version_farmersdelight=6154807
# Farming For Blockheads: 21.1.7
version_farmingforblockheads=6185977
# FTB Industrial Contraptions: 1900.1.7-build.212
#version_ftb_industrial_contraptions=3907201
# Ice and Fire: 2.1.13-1.20.1-beta-5
version_iceandfire=5633453
version_immersiveengineering=1.21.1-12.2.0-187
version_industrialforegoing=1.21-3.6.24
# Mana and Artifice: 3.0.0.9
version_manaandartifice=5121096
#version_mrcrayfishs_vehicle_mod=3103940
# Mystical Agriculture: 8.0.13
version_mysticalagriculture=6228700
# Nature's Aura: 41.6
version_naturesaura=5966337
version_occultism=1.21.1-neoforge:1.177.1
# HC Food Core: 1.0.0
version_pamsharvestcraftfoodcore=6155923
# HC Food Crops: 1.0.0
version_pamsharvestcraftcrops=6221524
# HC Food Extended: 1.0.0
version_pamsharvestcraftfoodextended=6221521
version_pneumaticcraft=8.2.12+mc1.21.1
#version_psi=1.16-95.416
#version_thermal_core=10.2.0.+
#version_thermalcultivation=10.2.0.+
#version_thermalexpansion=10.2.0.+
#version_thermalfoundation=10.2.0.+
#version_thermalinnovation=10.2.0.+
#version_thermalintegration=10.2.0.+
#version_thermallocomotion=10.2.0.+
#version_tinkers=1.16.5-3.2.1.297
# Tohou Little Maid: 1.21.1-release-1.2.1
version_touhou_little_maid=6302619
#version_woot=3383734
