# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# Configuration cache fails with modpublisher as it did with minotaur
org.gradle.configuration-cache=false

# Env Details
mc_version=1.21.1
mc_version_range=[1.21.1,1.22)
neo_version=21.1.206
neo_version_range=[21.1.206,)
loader_version_range=[1,)
mapping_channel=parchment
parchment_mc_version=1.21.1
parchment_map_version=2024.11.17

# Mod Details
mod_id=projecteintegration
mod_name=ProjectE-Integration
mod_version=8.2.0
mod_license=MIT
mod_group_id=com.tagnumelite.projecteintegration
mod_authors=TagnumElite
mod_description=ProjectE Integration is a mod for adding support for mapping recipes from other mods to something that ProjectE understands and is able to convert to emc with.

# ==== [ Project Dependencies ] ====
projecte_version=PE1.0.0B
version_projecte=6301953

# - Runtime
version_jade=15.10.5+neoforge
version_jei=19.21.1.304

# AE JEI: 1.2.0
version_ae_jei=5748513
version_architectury=13.0.8
# Athena: 4.0.1
version_athena=5629395
# Balm: 21.0.33
version_balm=6319698
version_brandonscore=3.2.1.309
version_codechickenlib=4.6.1.+
version_cucumber=8.0.10
version_curios=9.5.1
# Cyclops Core: 1.25.7
version_cyclopscore=6230091
version_geckolib=4.7.5.1
version_guideme=21.1.15
# Jupiter: 2.3.7
version_jupiter=7738312
#version_mantle=1.18.2-1.9.9
version_modonomicon=1.114.0
version_patchouli=1.21-88-NEOFORGE
version_patchouli_provider=1.0.11-Snapshot.5
# Resourceful Lib: NeoForge-3.0.12
version_resourceful_lib=5973188
version_titanium=1.21-4.0.28
version_smartbrainlib=1.16.11
# Uranus: 2.4
version_uranus=6979353

# - Optional
version_actually_additions=1.3.25
version_appliedenergistics=19.2.4
# Ars Nouveau: 5.7.1
version_arsnouveau=6316304
# Chipped: 4.0.2
version_chipped=5813117
# Corail Woodcutter: 3.4.2
version_corail_woodcutter=5749639
version_create=6.0.9
version_draconicevolution=3.1.4.632
# EvilCraft: 1.2.68
version_evilcraft=6296089
version_exnihilo_sequentia=1.21-7.0.0-build.1-beta
version_extendedcrafting=7.0.3
# Farmer's Delight: 1.2.7
version_farmersdelight=6154807
# Farming For Blockheads: 21.1.7
version_farmingforblockheads=6185977
# Ice and Fire Community Edition: 2.0-beta.15-1.21.1
version_iceandfirece=7722420
version_immersiveengineering=1.21.1-12.2.0-187
version_industrialforegoing=1.21-3.6.24
# Mystical Agriculture: 8.0.13
version_mysticalagriculture=6228700
# Nature's Aura: 41.6
version_naturesaura=5966337
version_occultism=1.21.1-neoforge:1.177.1
# HC Food Core: 1.0.0
version_pamsharvestcraftfoodcore=6155923
# HC Food Extended: 1.0.0
version_pamsharvestcraftfoodextended=6221521
version_pneumaticcraft=8.2.12+mc1.21.1
version_psi=1.21.1-108
# Tohou Little Maid: 1.21.1-release-1.2.1
version_touhou_little_maid=6302619
# Woot Revived: 21.1.1.9
version_woot_revived=7678371
