package com.tagnumelite.projecteintegration;

public class Reference {
    public static final String DEPENDENCIES = "required-after:projecte;"
                                                     + "after:actuallyadditions;"
                                                     + "after:appliedenergistics2;"
                                                     + "after:armorplus;"
                                                     + "after:astralsorcery;"
                                                     + "after:avaritia;"
                                                     + "after:bloodmagic;"
                                                     + "after:botania;"
                                                     + "after:calculator;"
                                                     + "after:compactmachines3;"
                                                     + "after:charset;"
                                                     + "after:draconicevolution;"
                                                     + "after:embers;"
                                                     + "after:enderio;"
                                                     + "after:extendedcrafting;"
                                                     + "after:extrabotany;"
                                                     + "after:forestry;"
                                                     + "after:ic2;"
                                                     + "after:immersiveengineering;"
                                                     + "after:mysticalagriculture;"
                                                     + "after:nuclearcraft;"
                                                     + "after:reborncore;"
                                                     + "after:techreborn;"
                                                     + "after:thaumcraft;"
                                                     + "after:thermalexpansion;"
                                                     + "after:tconstruct;";
}
