name: Build Mod and Deploy Docs

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: 'gradle'

            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@v1

            - run: ./gradlew build javadoc

            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                name: projecte-integration-jars
                path: build/libs/*.jar

            - name: Deploy Docs if push
              uses: JamesIves/github-pages-deploy-action@v4.4.2
              if: ${{ github.event_name == 'push' }}
              with:
                  branch: gh-pages
                  folder: build/docs/javadoc

            - name: Archive javadoc results
              uses: actions/upload-artifact@v3
              with:
                name: javadocs
                path: build/docs/javadoc/
