# Just to let you know, this has mostly been ~stolen~ copied from https://github.com/CompactMods/CompactCrafting/blob/1.16.x/.github/workflows/tagged-release.yml
# Why? Just because I'm lazy, that's about it.
name: Release Latest 8.*.* Version

on:
  push:
    tags:
    - v8*
  workflow_dispatch:

jobs:
  buildAndPublish:
    name: Build Jars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Publish JAR with Gradle
        run: ./gradlew build publishMod publish
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_API_KEY }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

      - name: Upload Jars
        uses: actions/upload-artifact@v4
        with:
          name: libs
          path: build/libs/*.jar
